image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

stages:
  - build
  - static-analysis
  - test

build:
  stage: build
  script:
    - python --version
    - python setup.py install
    - pip install pylint pytest

static-analysis:
  stage: static-analysis
  allow_failure: true
  script:
    - pylint opendc

test:
  stage: test
  script:
    - pytest
