version: "3.8"

# Docker Compose overrides for production environments
services:
  frontend:
    ports:
      - "8080:80"
    environment:
      REACT_APP_API_BASE_URL: ${OPENDC_API_BASE_URL}

  api:
    ports:
      - "8081:8081"
    environment:
      SENTRY_ENVIRONMENT: "production"

  simulator:
    environment:
      SENTRY_ENVIRONMENT: "production"
