version: "3"
services:
  frontend:
    build: ./
    image: frontend
    restart: on-failure
    ports:
      - "8081:8081"
    links:
      - mariadb
    depends_on:
      - mariadb
    environment:
      - MYSQL_DATABASE=opendc
      - MYSQL_USER=opendc
      - MYSQL_PASSWORD=opendcpassword
  simulator:
    build:
        context: ./opendc-simulator
        dockerfile: opendc-model-odc/setup/Dockerfile
    image: simulator
    restart: on-failure
    links:
      - mariadb
    depends_on:
      - mariadb
    environment:
      - PERSISTENCE_URL=jdbc:mysql://mariadb:3306/opendc
      - PERSISTENCE_USER=opendc
      - PERSISTENCE_PASSWORD=opendcpassword
      - COLLECT_MACHINE_STATES=ON
      - COLLECT_TASK_STATES=ON
      - COLLECT_STAGE_MEASUREMENTS=OFF
      - COLLECT_TASK_METRICS=OFF
      - COLLECT_JOB_METRICS=OFF
  mariadb:
    build:
        context: ./database
    image: database
    restart: on-failure
    ports:
      - "3306:3306" # comment this line out in production
    environment:
      - MYSQL_DATABASE=opendc
      - MYSQL_USER=opendc
      - MYSQL_PASSWORD=opendcpassword
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    # uncomment in production
    # volumes:
    #   - "/data/mariadb:/var/lib/mysql"
