version: "3.8"

# Docker Compose overrides for production environments
services:
  frontend:
    ports:
      - "8080:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: ${OPENDC_API_BASE_URL}

  api:
    ports:
      - "8081:80"
    environment:
      SENTRY_ENVIRONMENT: "production"

  simulator:
    environment:
      SENTRY_ENVIRONMENT: "production"
