version: "3.8"

# Docker Compose overrides for development environments
services:
  ui:
    build: opendc-web/opendc-web-ui
    ports:
      - "8080:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8081

  server:
    build:
      context: .
      dockerfile: opendc-web/opendc-web-server/Dockerfile
    ports:
      - "8081:8080"
    environment:
      SENTRY_ENVIRONMENT: "development"

  postgres:
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    networks:
      - backend
    depends_on:
      - postgres
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'

volumes:
  pgadmin:
