version: "3"
services:
  mongo:
    build:
        context: ./
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: admin
      OPENDC_DB: opendc
      OPENDC_DB_USERNAME: opendc
      OPENDC_DB_PASSWORD: opendcpassword
    ports:
      - 27017:27017
    # Uncomment for persistent deployment
    #volumes:
    #  - mongo-volume:/data/db

  mongo-express:
    image: mongo-express
    restart: on-failure
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword

volumes:
    mongo-volume:
        external: false
