name: Frontend

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Node.js
                uses: actions/setup-node@v1
                with:
                    node-version: 12.x
            -   run: npm install
                working-directory: frontend
            -   run: npm run build --if-present
                working-directory: frontend
            -   run: npm test
                working-directory: frontend
                env:
                    CI: true
